In [113]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')   
import plotly.express as px
%matplotlib inline

In [114]:
df=pd.read_csv('cardekho_imputated.csv',index_col=0)

In [115]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [116]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [117]:
df.drop('car_name',axis=1,inplace=True)
df.drop('brand',axis=1,inplace=True)

In [118]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [119]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [120]:
num_features = [features for features in df.columns if df[features].dtypes != 'O']
print('Number of numerical features: ', len(num_features))
cat_features = [features for features in df.columns if df[features].dtypes == 'O']
print('Number of categorical features: ', len(cat_features))
dis_features = [features for features in df.columns if len(df[features].unique()) < 25 and df[features].dtypes != 'O']
print('Number of discrete features: ', len(dis_features))
con_features = [features for features in df.columns if len(df[features].unique()) >= 25 and df[features].dtypes != 'O']
print('Number of continuous features: ', len(con_features))

Number of numerical features:  7
Number of categorical features:  4
Number of discrete features:  2
Number of continuous features:  5

In [121]:
X=df.drop(['selling_price'], axis=1)
y=df['selling_price']

In [122]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [123]:
y.head()

0    120000
1    550000
2    215000
3    226000
4    570000
Name: selling_price, dtype: int64

In [124]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [125]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [126]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [127]:
num_features=X.select_dtypes(exclude="object").columns
onehot_columns= ['seller_type', 'fuel_type', 'transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer= StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StnadrdScaler", numeric_transformer, num_features)
    ], remainder='passthrough'
)

In [128]:
X=preprocessor.fit_transform(X)

In [129]:
X=pd.DataFrame(X)

In [130]:
X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [131]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [132]:
X_train

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
11210,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.261053,0.319814,0.283541,-2.038093,1.753906,2.662498,-0.403022
1347,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.793003,-1.339555,-0.883751,0.992261,-0.550880,-0.386028,-0.403022
10363,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.244390,-1.339555,-0.961245,-0.168096,0.890331,3.274530,-0.403022
316,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.024131,0.319814,0.143045,-0.455788,0.020999,0.388902,-0.403022
10638,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,1.315436,0.478051,0.157955,-0.554718,-0.504712,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5191,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.556082,0.319814,1.397111,0.256249,-0.456846,-0.274327,2.073444
13418,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.903133,1.647309,0.065551,-0.865749,0.214823,0.060778,-0.403022
5390,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.040794,0.319814,-0.690016,0.193916,-0.936610,-0.780708,-0.403022
860,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,-1.339555,-0.786884,-0.263994,-0.554718,-0.435829,-0.403022
7270,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.051664,-1.339555,-0.496281,0.138775,-0.046168,0.061942,-0.403022

In [133]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [134]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    score = r2_score(true, predicted)
    return mae, mse, rmse, score

In [135]:
models={
       "Linear Regression": LinearRegression(),
       "Lasso": Lasso(),
       "Ridge": Ridge(),
       "KNN Regressor": KNeighborsRegressor(),
       "Decision Tree": DecisionTreeRegressor(),
       "Random Forest": RandomForestRegressor()
}

for model_name, model in models.items():
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(model_name)
    print("Model Performance on Training Set")
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- RMSE: {:.4f}".format(model_train_rmse))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('--------------------------------')

    print("Model Performance on Test Set")
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- RMSE: {:.4f}".format(model_test_rmse))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('=' * 50)
    print('\n\n')

Linear Regression
Model Performance on Training Set
- Mean Absolute Error: 268101.6071
- RMSE: 553855.6665
- R2 Score: 0.6218
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 279618.5794
- RMSE: 502543.5930
- R2 Score: 0.6645
==================================================



Lasso
Model Performance on Training Set
- Mean Absolute Error: 268099.2226
- RMSE: 553855.6710
- R2 Score: 0.6218
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 279614.7461
- RMSE: 502542.6696
- R2 Score: 0.6645
==================================================



Ridge
Model Performance on Training Set
- Mean Absolute Error: 268059.8015
- RMSE: 553856.3160
- R2 Score: 0.6218
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 279557.2169
- RMSE: 502533.8230
- R2 Score: 0.6645
==================================================



KNN Regressor
Model Performance on Training Set
- Mean Absolute Error: 91425.4705
- RMSE: 325873.0088
- R2 Score: 0.8691
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 112526.3461
- RMSE: 253024.3951
- R2 Score: 0.9150
==================================================



Decision Tree
Model Performance on Training Set
- Mean Absolute Error: 5164.8199
- RMSE: 20797.2352
- R2 Score: 0.9995
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 125610.4092
- RMSE: 310784.2578
- R2 Score: 0.8717
==================================================



Random Forest
Model Performance on Training Set
- Mean Absolute Error: 39962.9420
- RMSE: 139952.8331
- R2 Score: 0.9758
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 101381.3685
- RMSE: 225097.6529
- R2 Score: 0.9327
==================================================

In [136]:
knn_params = {"n_neighbors": [2,3,10,20,40,50]}
rf_params = {"max_depth": [5,8,15,None,10],
            "max_features": [5,7,"auto",8],
            "min_samples_split": [2,8,15,20],
            "n_estimators": [100,200,500,1000]}

In [137]:
randomcv_models = [('KNN', KNeighborsRegressor(), knn_params),
                   ('RF', RandomForestRegressor(), rf_params)
                   
                   ]

In [143]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                n_iter=100,
                                cv=3,
                                verbose=2,
                                n_jobs=-1)
    random.fit(X_train, y_train)  
    model_param[name]= random.best_params_  

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} ----------")                      
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for KNN ----------
{'n_neighbors': 10}
---------------- Best Params for RF ----------
{'n_estimators': 200, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 15}

In [145]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=200, min_samples_split=2, max_features=8, max_depth= 15, n_jobs=-1),
    "KNN": KNeighborsRegressor(n_neighbors= 10, n_jobs=-1)
}   
for model_name, model in models.items():
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(model_name)
    print("Model Performance on Training Set")
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- RMSE: {:.4f}".format(model_train_rmse))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('--------------------------------')

    print("Model Performance on Test Set")
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- RMSE: {:.4f}".format(model_test_rmse))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('=' * 50)
    print('\n\n')

Random Forest
Model Performance on Training Set
- Mean Absolute Error: 53802.2126
- RMSE: 129470.2080
- R2 Score: 0.9793
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 98148.8764
- RMSE: 216444.8741
- R2 Score: 0.9378
==================================================



KNN
Model Performance on Training Set
- Mean Absolute Error: 103472.0474
- RMSE: 363460.7706
- R2 Score: 0.8371
--------------------------------
Model Performance on Test Set
- Mean Absolute Error: 117496.2131
- RMSE: 263888.0623
- R2 Score: 0.9075
==================================================